name: .NET

on:
  push:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'Giantnodes.Dashboard.sln'
      - '**/dotnet.yml'
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'Giantnodes.Dashboard.sln'
      - '**/dotnet.yml'
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore
   
    - name: Test
      run: dotnet test --no-build --verbosity normal
