name: .NET

on:
  push:
    paths:
      - 'src/**'
      - '**/dotnet.yml'
  pull_request:
    paths:
      - 'src/**'
      - '**/dotnet.yml'
  workflow_dispatch:

jobs:
  test-dashboard:
    name: Dashboard
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    
    - name: Restore dependencies
      run: dotnet restore
      working-directory:  src/Dashboard
    
    - name: Build
      run: dotnet build --no-restore
      working-directory:  src/Dashboard
   
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: src/Dashboard
